### ISSUE TITLE
Missing folders defined by default values

### ISSUE THREAD

**Issue by hxpro** [hxpro/ansible-role-phpfpm#1]
``` yaml
- name: Create folders defined in default vars
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: apache
    mode: '0770'
    seuser: 'system_u'
    setype: 'httpd_var_lib_t'
  with_items:
    - "/var/lib/php/session"
    - "/var/lib/php/wsdlcache"
    - "/var/lib/php/opcache"
```
